crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from profiles import views as profiles_views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('crm/', include('crm_app.urls')),
	path('', RedirectView.as_view(url='/crm/', permanent=True)),
    path('profile/', profiles_views.profile, name='profile'),   
    path('accounts/', include('django.contrib.auth.urls')), 
    path('tinymce/', include('tinymce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('', views.CompanyListView.as_view(), name='index'),
	path('company/<int:pk>/projects/', views.ProjectListView.as_view(), name='projects'),
	path('company/<int:pk>/messages/', views.MessageCompanyListView.as_view(), name='comp_messages'),
	path('company/<int:pk>', views.CompanyDetailView.as_view(), name='company_detail'),
	path('company/create/', views.CompanyCreate.as_view(), name='company_create'),
    path('company/<int:pk>/update/', views.CompanyUpdate.as_view(), name='company_update'),
	path('project/<int:pk>', views.ProjectDetailView.as_view(), name='project_detail'),
	path('project/<int:pk>/messages/', views.MessageProjectListView.as_view(), name='proj_messages'),
	path('project/create/', views.ProjectCreate.as_view(), name='project_create'),
    path('project/<int:pk>/update/', views.ProjectUpdate.as_view(), name='project_update'),
	path('message/<int:pk>', views.MessageDetailView.as_view(), name='message_detail'),
	path('message/create/', views.MessageCreate.as_view(), name='message_create'),
    path('message/<int:pk>/update/', views.MessageUpdate.as_view(), name='message_update'),
	path('messages/', views.UsersMessageListView.as_view(), name='users_messages'),

]
																										

crm_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from datetime import date
# Create your models here.

class Company(models.Model):
	"""Company model."""
	name = models.CharField('Компания', max_length=200)
	director = models.CharField('Директор', max_length=200)
	description = HTMLField('Описание')
	date_create = models.DateField('Дата создания записи', auto_now_add=True)
	date_edit = models.DateField('Дата редактирования записи', auto_now=True)

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return self.name

	def get_absolute_url(self):
		return reverse('company_detail', args=[str(self.id)])

	class Meta:
		verbose_name_plural='Компании'
		verbose_name='Компания'
		ordering = ['name']


class Address(models.Model):
	"""Address model."""
	company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, verbose_name='Компания')
	address = models.CharField('Адрес', max_length=200)

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return self.address

	class Meta:
		verbose_name_plural='Адрес'
		verbose_name='Адрес'


class Phone(models.Model):
	"""Phone model."""	
	company =  models.ForeignKey(Company, on_delete=models.CASCADE, null=True, verbose_name='Компания')
	phone_number = models.CharField('Тел.номер', max_length=17, blank=True)

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return self.phone_number

	class Meta:
		verbose_name_plural='Тел.номер'
		verbose_name='Тел.номер'


class Email(models.Model):
	"""Email model"""
	company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, verbose_name='Компания')
	email =  models.EmailField('Эл.почта')

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return self.email

	class Meta:
		verbose_name_plural='Эл.почта'
		verbose_name='Эл.почта'
	
		
class Project(models.Model):
	"""Project model"""
	company = models.ForeignKey(Company, on_delete=models.PROTECT, null=True, verbose_name='Компания')
	name = models.CharField('Проект', max_length=200)
	description = models.TextField('Описание')
	date_start = models.DateField('Дата начала', default=date.today)
	date_finish = models.DateField('Дата окончания', null=True, blank=True)
	cost = models.DecimalField('Стоимость', max_digits=8, decimal_places=2)

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return self.name

	def get_absolute_url(self):
		return reverse('project_detail', args=[str(self.id)])

	class Meta:
		verbose_name_plural='Проекты'
		verbose_name='Проект'
		ordering = ['-name']


class Message(models.Model):
	"""Message model"""
	project = models.ForeignKey(Project, on_delete=models.PROTECT, null=True, verbose_name='Проект')
	manager =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Менеджер')
	description = models.TextField('Описание')
	date_time = models.DateTimeField('Дата и время', auto_now_add=True)
	CHANNEL = (
		('p', 'Звонок по телефону'),
		('e', 'Email'),
		('m', 'Мессенджер'),
		('s', 'Заявка через сайт'),
		('c', 'Инициатива нашей компании')
		)
	circulation_channel = models.CharField('Канал взаимодействия', max_length=1, choices=CHANNEL)
	RATING = (
		('vg', 'Отлично'),
		('g', 'Хорошо'),
		('n', 'Нейтрально'),
		('b', 'Плохо'),
		('vb', 'Очень плохо')

		)
	rating = models.CharField('Оценка', max_length=2, choices=RATING)

	def __str__(self):
		"""
		String for representing the Model object
		"""
		return '%s (%s)' % (self.project.name, self.description[:30])

	def get_absolute_url(self):
		return reverse('message_detail', args=[str(self.id)])

	class Meta:
		verbose_name_plural='Взаимодействия'
		verbose_name='Взаимодействие'






	
		
	
		

crm_app/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Company, Address, Phone, Email


AddressFormSet = inlineformset_factory(Company, Address, form=forms.ModelForm, fields=('address',), extra=2)
PhoneFormSet = inlineformset_factory(Company, Phone, form=forms.ModelForm, fields=('phone_number',), extra=2)
EmailFormSet = inlineformset_factory(Company, Email, form=forms.ModelForm, fields=('email',), extra=2)


class CompanyForm(forms.ModelForm):
    """A class used to create the form for companies

    Attributes (Meta):
        model (class): Database's table
        fields (list): List of fields.
    """  
    class Meta:
        model = Company
        fields = ('name', 'director', 'description')

crm_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.forms import formset_factory
from .models import Company, Address, Phone, Email, Project, Message
from .forms import CompanyForm, AddressFormSet, PhoneFormSet, EmailFormSet


# Create your views here.


class CompanyListView(LoginRequiredMixin, generic.ListView):
    """A class used to represent all companies

    Attributes:
        model (class): Database's table
        paginate_by (int): Number of records on the page
        template_name (str): Name of html template for rendering
    """
    model = Company
    paginate_by = 3
    template_name = 'index.html'


    def get_ordering(self):
        """Method sort records on the page

        Attributes:
            ordering (QuerySet): Sorted list of companies
        """
        ordering = self.request.GET.get('orderby')
        return ordering


class CompanyDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    """A class used to represent information of company

    Attributes:
        model (var): Database's table
        permission_required (str): Page access for manager and administrators
    """
    model = Company
    permission_required = 'crm_app.view_company'


class ProjectDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    """A class used to represent information of project

    Attributes:
        model (class): Database's table
        permission_required (str): Page access for manager and administrators
    """
    model = Project
    permission_required = 'crm_app.view_project'


class MessageDetailView(PermissionRequiredMixin, generic.DetailView):
    """A class used to represent information of message

    Attributes:
        model (class): Database's table
        permission_required (str): Page access for manager and administrators
    """
    model = Message
    permission_required = 'crm_app.view_message'



class ProjectListView(PermissionRequiredMixin, generic.ListView):
    """A class used to represent all projects of company

    Attributes:
        template_name (str): Name of html template for rendering
        permission_required (str): Page access for manager and administrators
    """
    template_name = 'crm_app/project_list.html'
    permission_required = 'crm_app.view_project'
    def get_queryset(self):
        """Overriding QuerySet

        Returns:
            QuerySet of projects.
            Can be sorted.
        """
        self.company = get_object_or_404(Company, pk=self.kwargs['pk'])
        return Project.objects.filter(company=self.company).order_by(self.request.GET.get('orderby', 'name'))

    def get_context_data(self, **kwargs):
        """Get the context for this view.

        Returns:
            Context.
        """
        context = super().get_context_data(**kwargs)
        context['company'] = self.company
        context['pk'] = self.kwargs['pk']
        return context


class MessageCompanyListView(PermissionRequiredMixin, generic.ListView):
    """A class used to represent all messages of company

    Attributes:
        template_name (str): Name of html template for rendering
        permission_required (str): Page access for manager and administrators
    """
    template_name = 'crm_app/comp_message_list.html'
    permission_required = 'crm_app.view_message'

    def get_queryset(self):
        """Overriding QuerySet

        Returns:
            QuerySet of messages.
            Can be sorted and filtered.
        """
        self.company = get_object_or_404(Company, pk=self.kwargs['pk'])
        return Message.objects.filter(project__company=self.company).\
        order_by(self.request.GET.get('orderby', 'date_time')).\
        filter(description__contains=self.request.GET.get('filter', ''))

    def get_context_data(self, **kwargs):
        """Get the context for this view.

        Returns:
            Context.
        """
        context = super().get_context_data(**kwargs)
        context['company'] = self.company
        context['pk'] = self.kwargs['pk']
        return context


class MessageProjectListView(PermissionRequiredMixin, generic.ListView):
    """A class used to represent all messages of project

    Attributes:
        template_name (str): Name of html template for rendering
        permission_required (str): Page access for manager and administrators
    """
    template_name = 'crm_app/proj_message_list.html'
    permission_required = 'crm_app.view_message'

    def get_queryset(self):
        """Overriding QuerySet

        Returns:
            QuerySet of messages.
            Can be sorted and filtered.
        """
        self.project = get_object_or_404(Project, pk=self.kwargs['pk'])
        return Message.objects.filter(project=self.project).\
        order_by(self.request.GET.get('orderby', 'date_time')).\
        filter(description__contains=self.request.GET.get('filter', ''))

    def get_context_data(self, **kwargs):
        """Get the context for this view.

        Returns:
            Context.
        """
        context = super().get_context_data(**kwargs)
        context['project'] = self.project
        context['pk'] = self.kwargs['pk']
        return context


class CompanyCreate(PermissionRequiredMixin, CreateView):
    """A class used to create a company

    Attributes:
        model (class): Database's table
        form_class (class): Class inherit from ModelForm
        permission_required (str): Page access for manager and administrators
    """
    model = Company
    form_class = CompanyForm
    permission_required = 'crm_app.add_company'


    def get(self, request, *args, **kwargs):
        """
        Handles GET requests and instantiates blank versions of the form
        and its inline formsets.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        address_form = AddressFormSet()
        phone_form = PhoneFormSet()
        email_form = EmailFormSet()
        return self.render_to_response(
            self.get_context_data(form=form,
                                  address_form=address_form,
                                  phone_form=phone_form,
                                  email_form=email_form))

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance and its inline
        formsets with the passed POST variables and then checking them for
        validity.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        address_form = AddressFormSet(self.request.POST)
        phone_form = PhoneFormSet(self.request.POST)
        email_form = EmailFormSet(self.request.POST)
        if (form.is_valid() and address_form.is_valid() and
            phone_form.is_valid() and email_form.is_valid()):
            return self.form_valid(form, address_form, phone_form, email_form)
        else:
            return self.form_invalid(form, address_form, phone_form, email_form)

    def form_valid(self, form, address_form, phone_form, email_form):
        """
        Called if all forms are valid. Creates a Company instance along with
        associated Address and Phones and Emails and then redirects to a
        success page.
        """
        self.object = form.save()
        address_form.instance = self.object
        address_form.save()
        phone_form.instance = self.object
        phone_form.save()
        email_form.instance = self.object
        email_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, address_form, phone_form, email_form):
        """
        Called if a form is invalid. Re-renders the context data with the
        data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form,
                                  address_form=address_form,
                                  phone_form=phone_form,
                                  email_form=email_form))



class CompanyUpdate(PermissionRequiredMixin, UpdateView):
    """A class used to update a company

    Attributes:
        model (class): Database's table
        form_class (class): Class inherit from ModelForm
        permission_required (str): Page access for manager and administrators
    """
    model = Company
    form_class = CompanyForm
    permission_required = 'crm_app.change_company'

    # def get_success_url(self):
    #     return reverse_lazy('company_detail')


    def get_context_data(self, **kwargs):
        """Overriding QuerySet

        Returns:
            QuerySet of companies with addresses, phones and emails.
        """
        context = super(CompanyUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context["address_form"] = AddressFormSet(self.request.POST, instance=self.object)
            context["phone_form"] = PhoneFormSet(self.request.POST, instance=self.object)
            context["email_form"] = EmailFormSet(self.request.POST, instance=self.object)
        else:
            context["address_form"] = AddressFormSet(instance=self.object)
            context["phone_form"] = PhoneFormSet(instance=self.object)
            context["email_form"] = EmailFormSet(instance=self.object)
        return context

    def get(self, request, *args, **kwargs):
        """
        Handles GET requests and instantiates blank versions of the form
        and its inline formsets.
        """
        self.object = self.get_object()
        form_class = self.get_form_class()

crm_app/templates/crm_app/comp_message_list.html
{% extends "base_generic.html" %}
{% block title %}<title>Взаимодействия по {{ company }}</title>{% endblock %}
{% block sort %} 
<form action="" method="get" id="sortProduct">
<div class="dropdown">
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Сортировать
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="?orderby=description">По тексту сообщения</a>
          <a class="dropdown-item" href="?orderby=-description">По тексту сообщения(в обратном порядке)</a>
          <a class="dropdown-item" href="?orderby=date_time">По времени создания </a>
          <a class="dropdown-item" href="?orderby=-date_time">По времени создания(в обратном порядке)</a>
        </div>
      </li>
</div>
</form>
{% endblock %}
{% block filter %}
<form action="" method="get" id="sortProduct">
<div class="dropdown">
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Фильтр
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="?filter=Lorem">Lorem</a>
	  <a class="dropdown-item" href="?filter=Curabitur">Curabitur</a>
	  <a class="dropdown-item" href="?filter=fermentum">fermentum</a>
	  <a class="dropdown-item" href="?filter=sapien">sapien</a>
        </div>
  </li>
</div>
</form>
{% endblock %}
{% block button %}<a class="nav-item nav-link" href="{% url 'message_create' %}">Добавить взаимодействие</a>{% endblock %}
{% block content %}
	<h3>Все взаимодействия по компании <a href="{% url 'company_detail' pk %}">{{ company }}</a>:</h3>
	<ul>
      {% for message in message_list %}
      <li> 
          <div class="row">
            <div class="col-sm-8">
              <p><a href="{{ message.get_absolute_url }}">{{ message.description|slice:":100" }}</a></p>
              <p> {{ message.date_time }} </p>
            </div>
            <div class="col-sm-4">
              <p>Добавил : {{ message.manager.first_name }} {{ message.manager.last_name }}</p>
              <p>Оценка: {{ message.get_rating_display }}</p>
            </div>
          </div> 
        </li>
      <hr>     
      {% endfor %}
    </ul>
{% endblock %}

crm_app/templates/crm_app/company_detail.html
{% extends "base_generic.html" %} 
{% block title %}<title>{{ company.name }}</title>{% endblock %}
{% block button %}<a class="nav-item nav-link" href="{% url 'company_update' company.pk %}">Редактировать</a>{% endblock %}
{% block button2 %}<a class="nav-item nav-link" href="{% url 'project_create' %}">Добавить проект</a>{% endblock %}
{% block content %}
  <h1>{{ company.name }}</h1>
  <p><strong>Директор:</strong> {{ company.director }}</a></p> 
  <p><strong>Описание:</strong> {{ company.description }}</p>
  <p><strong>Телефон:</strong> {% for phone in company.phone_set.all %} {{ phone }}  {% endfor %}</p>
  <p><strong>Адрес:</strong> {% for address in company.address_set.all %} {{ address }}  {% endfor %}</p>
  <p><strong>Email:</strong> {% for email in company.email_set.all %} {{ email }}  {% endfor %}</p>
  {% if company.project_set.all %}
  <div>
    <p><a href="{% url 'projects' company.pk %}"> Все проекты по компании</a></p>
    <p><a href="{% url 'comp_messages' company.pk %}">Все взаимодействия по компании</a></p>
  </div>
  <div>
    <h3>Проекты:</h3>
    <ul>
      {% for project in company.project_set.all %}
      <li>
        <a href="{{ project.get_absolute_url }}">{{ project.name }}</a>
      </li>
        <br>
      {% endfor %}
    </ul>
    {% else %}
    <h3>У этой компании ещё нет проектов.</h3>
    {% endif %}      
  </div> 
{% endblock %}

crm_app/templates/crm_app/company_form.html
{% extends "base_generic.html" %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <div class="inline">
    <p>{{ address_form.as_table }}</p>
    <p>{{ phone_form.as_table }}</p>
    <p>{{ email_form.as_table }}</p>
    </div>
    <input type="submit" value="Submit" />
</form>
{% endblock %}

crm_app/templates/crm_app/message_detail.html
{% extends "base_generic.html" %}
{% block title %}<title>Message</title>{% endblock %}
{% block button %}{% if user == message.manager %}<a class="nav-item nav-link" href="{% url 'message_update' message.pk %}">Редактировать</a>{% endif %}{% endblock %}
{% block content %}
  <p><strong>Проект:</strong> {{ message.project }}</p>
  <p><strong>Компания:</strong> {{ message.project.company }}</p>
  <p><strong>Менеджер:</strong> {{ message.manager.first_name }} {{ message.manager.last_name }}</p>
  <p><strong>Описание:</strong> {{ message.description }}</p>
  <p><strong>Дата и время:</strong> {{ message.date_time}}</p>
  <p><strong>Канал взаимодействия:</strong> {{ message.get_circulation_channel_display }} </p>
  <p><strong>Оценка:</strong> {{ message.get_rating_display }} </p>  
{% endblock %}

crm_app/templates/crm_app/message_form.html
{% extends "base_generic.html" %}

{% block content %}
<h3>Менеджер: {{ user.first_name }} {{ user.last_name }}</h3>
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

crm_app/templates/crm_app/proj_message_list.html
{% extends "base_generic.html" %}
{% block title %}<title>Взаимодействия по проекту</title>{% endblock %}
{% block sort %} 
<form action="" method="get" id="sortProduct">
<div class="dropdown">
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Сортировать
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="?orderby=description">По тексту сообщения</a>
          <a class="dropdown-item" href="?orderby=-description">По тексту сообщения(в обратном порядке)</a>
          <a class="dropdown-item" href="?orderby=date_time">По времени создания </a>
          <a class="dropdown-item" href="?orderby=-date_time">По времени создания(в обратном порядке)</a>
        </div>
      </li>
</div>
</form>
{% endblock %}
{% block filter %}
<form action="" method="get" id="sortProduct">
<div class="dropdown">
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Фильтр
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="?filter=Lorem">Lorem</a>
  	  <a class="dropdown-item" href="?filter=Curabitur">Curabitur</a>
  	  <a class="dropdown-item" href="?filter=fermentum">fermentum</a>
  	  <a class="dropdown-item" href="?filter=sapien">sapien</a>
    </div>
  </li>
</div>
</form>
{% endblock %}
{% block button %}<a class="nav-item nav-link" href="{% url 'message_create' %}">Добавить взаимодействие</a>{% endblock %}
{% block content %}
	<h4>Все взаимодействия по проекту "<a href="{{ project.get_absolute_url }}">{{ project }}</a>":</h4>
	<hr><hr>
	  <ul>
      {% for message in message_list %}
      	<li> 
          <div class="row">
            <div class="col-sm-8">
              <p><a href="{{ message.get_absolute_url }}">{{ message.description|slice:":100" }}</a></p>
              <p> {{ message.date_time }} </p>
            </div>
            <div class="col-sm-4">
              <p>Добавил : {{ message.manager.first_name }} {{ message.manager.last_name }}</p>
              <p>Оценка: {{ message.get_rating_display }}</p>
            </div>
          </div> 
        </li>
      <hr>     
      {% endfor %}
        </ul>
{% endblock %}

crm_app/templates/crm_app/project_detail.html
{% extends "base_generic.html" %}
{% block title %}<title>{{ project.name }}</title>{% endblock %}
{% block button %}<a class="nav-item nav-link" href="{% url 'project_update' project.pk %}">Редактировать</a>{% endblock %}
{% block button2 %}<a class="nav-item nav-link" href="{% url 'message_create' %}">Добавить взаимодействие</a>{% endblock %}
{% block content %}
  <h2>{{ project.name }}</h2>
  <p><strong>Компания:</strong> <a href="{{ project.company.get_absolute_url }}">{{ project.company }}</a></p>
  <p><strong>Описание:</strong> {{ project.description }}</p>
  <p><strong>Дата начала:</strong> {{project.date_start}}</p>
  {% if project.date_finish %}
    <p><strong>Дата окончания:</strong> {{ project.date_finish }}</p>
  {% endif %}
  <p><strong>Стоимость:</strong> {{ project.cost }}</p>
  {% if project.message_set.all %} 
    <p><strong><a href="{% url 'proj_messages' project.pk %}">Взаимодействия по проекту:</a></strong></p>
    <ul>
    {% for message in project.message_set.all %} 
      <li>
      <p> <a href="{{ message.get_absolute_url }}">{{ message.description|slice:":50" }}</a> </p>
      <p> {{ message.date_time }} </p>  
      </li>
    {% endfor %}
    </ul>
  {% else %}
    <h3>У этого проекта ещё нет взаимодействий.</h3>
  {% endif %}  
{% endblock %}

crm_app/templates/crm_app/project_form.html
{% extends "base_generic.html" %}

{% block content %}


<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />

</form>
{% endblock %}

crm_app/templates/crm_app/users_message_list.html
{% extends "base_generic.html" %}
{% block title %}<title>Messages</title>{% endblock %}
{% block sort %} 
<form action="" method="get" id="sortProduct">
<div class="dropdown">
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Сортировать
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="?orderby=description">По тексту сообщения</a>
          <a class="dropdown-item" href="?orderby=-description">По тексту сообщения(в обратном порядке)</a>
          <a class="dropdown-item" href="?orderby=date_time">По времени создания </a>
          <a class="dropdown-item" href="?orderby=-date_time">По времени создания(в обратном порядке)</a>
        </div>
      </li>
</div>
</form>
{% endblock %}
{% block filter %}
<form action="" method="get" id="sortProduct">
<div class="dropdown">
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Фильтр
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
      <a class="dropdown-item" href="?filter=Lorem">Lorem</a>
  	  <a class="dropdown-item" href="?filter=Curabitur">Curabitur</a>
  	  <a class="dropdown-item" href="?filter=fermentum">fermentum</a>
  	  <a class="dropdown-item" href="?filter=sapien">sapien</a>
    </div>
  </li>
</div>
</form>
{% endblock %}
{% block button %}<a class="nav-item nav-link" href="{% url 'message_create' %}">Добавить взаимодействие</a>{% endblock %}
{% block content %}
	<h4>Все взаимодействия, которые добавил менеджер: {{ user.first_name }} {{ user.last_name }}</h4>
	<hr><hr>
	  <ul>
      {% for message in message_list %}
      	<li> 
          <div class="row">
            <div class="col-sm-8">
              <p><a href="{{ message.get_absolute_url }}">{{ message.description|slice:":100" }}</a></p>
              <p> {{ message.date_time }} </p>
            </div>
            <div class="col-sm-4">
              <p>Добавил : {{ message.manager.first_name }} {{ message.manager.last_name }}</p>
              <p>Оценка: {{ message.get_rating_display }}</p>
            </div>
          </div> 
        </li>
      <hr>     
      {% endfor %}
        </ul>
{% endblock %}