crm/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from profiles import views as profiles_views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('crm/', include('crm_app.urls')),
	path('', RedirectView.as_view(url='/crm/', permanent=True)),
    path('profile/', profiles_views.profile, name='profile'),   
    path('accounts/', include('django.contrib.auth.urls')), 
    path('tinymce/', include('tinymce.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crm_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
	path('', views.CompanyListView.as_view(), name='index'),
	path('company/<int:pk>/projects/', views.ProjectListView.as_view(), name='projects'),
	path('company/<int:pk>/messages/', views.MessageCompanyListView.as_view(), name='comp_messages'),
	path('company/<int:pk>', views.CompanyDetailView.as_view(), name='company_detail'),
	path('company/create/', views.CompanyCreate.as_view(), name='company_create'),
    path('company/<int:pk>/update/', views.CompanyUpdate.as_view(), name='company_update'),
	path('project/<int:pk>', views.ProjectDetailView.as_view(), name='project_detail'),
	path('project/<int:pk>/messages/', views.MessageProjectListView.as_view(), name='proj_messages'),
	path('project/create/', views.ProjectCreate.as_view(), name='project_create'),
    path('project/<int:pk>/update/', views.ProjectUpdate.as_view(), name='project_update'),
	path('message/<int:pk>', views.MessageDetailView.as_view(), name='message_detail'),
	path('message/create/', views.MessageCreate.as_view(), name='message_create'),
    path('message/<int:pk>/update/', views.MessageUpdate.as_view(), name='message_update'),
	path('messages/', views.UsersMessageListView.as_view(), name='users_messages'),

]
																										

crm_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from datetime import date
# Create your models here.

class Company(models.Model):
	"""Company model."""
	name = models.CharField('Компания', max_length=200)
	director = models.CharField('Директор', max_length=200)
	description = HTMLField('Описание')
	date_create = models.DateField('Дата создания записи', auto_now_add=True)
	date_edit = models.DateField('Дата редактирования записи', auto_now=True)

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return self.name

	def get_absolute_url(self):
		return reverse('company_detail', args=[str(self.id)])

	class Meta:
		verbose_name_plural='Компании'
		verbose_name='Компания'
		ordering = ['name']


class Address(models.Model):
	"""Address model."""
	company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, verbose_name='Компания')
	address = models.CharField('Адрес', max_length=200)

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return self.address

	class Meta:
		verbose_name_plural='Адрес'
		verbose_name='Адрес'


class Phone(models.Model):
	"""Phone model."""	
	company =  models.ForeignKey(Company, on_delete=models.CASCADE, null=True, verbose_name='Компания')
	phone_number = models.CharField('Тел.номер', max_length=17, blank=True)

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return self.phone_number

	class Meta:
		verbose_name_plural='Тел.номер'
		verbose_name='Тел.номер'


class Email(models.Model):
	"""Email model"""
	company = models.ForeignKey(Company, on_delete=models.CASCADE, null=True, verbose_name='Компания')
	email =  models.EmailField('Эл.почта')

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return self.email

	class Meta:
		verbose_name_plural='Эл.почта'
		verbose_name='Эл.почта'
	
		
class Project(models.Model):
	"""Project model"""
	company = models.ForeignKey(Company, on_delete=models.PROTECT, null=True, verbose_name='Компания')
	name = models.CharField('Проект', max_length=200)
	description = models.TextField('Описание')
	date_start = models.DateField('Дата начала', default=date.today)
	date_finish = models.DateField('Дата окончания', null=True, blank=True)
	cost = models.DecimalField('Стоимость', max_digits=8, decimal_places=2)

	def __str__(self):
		"""
		String for representing the Model object.
		"""
		return self.name

	def get_absolute_url(self):
		return reverse('project_detail', args=[str(self.id)])

	class Meta:
		verbose_name_plural='Проекты'
		verbose_name='Проект'
		ordering = ['-name']


class Message(models.Model):
	"""Message model"""
	project = models.ForeignKey(Project, on_delete=models.PROTECT, null=True, verbose_name='Проект')
	manager =  models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, verbose_name='Менеджер')
	description = models.TextField('Описание')
	date_time = models.DateTimeField('Дата и время', auto_now_add=True)
	CHANNEL = (
		('p', 'Звонок по телефону'),
		('e', 'Email'),
		('m', 'Мессенджер'),
		('s', 'Заявка через сайт'),
		('c', 'Инициатива нашей компании')
		)
	circulation_channel = models.CharField('Канал взаимодействия', max_length=1, choices=CHANNEL)
	RATING = (
		('vg', 'Отлично'),
		('g', 'Хорошо'),
		('n', 'Нейтрально'),
		('b', 'Плохо'),
		('vb', 'Очень плохо')

		)
	rating = models.CharField('Оценка', max_length=2, choices=RATING)

	def __str__(self):
		"""
		String for representing the Model object
		"""
		return '%s (%s)' % (self.project.name, self.description[:30])

	def get_absolute_url(self):
		return reverse('message_detail', args=[str(self.id)])

	class Meta:
		verbose_name_plural='Взаимодействия'
		verbose_name='Взаимодействие'






	
		
	
		

crm_app/forms.py
from django import forms
from django.forms.models import inlineformset_factory
from .models import Company, Address, Phone, Email


AddressFormSet = inlineformset_factory(Company, Address, form=forms.ModelForm, fields=('address',), extra=2)
PhoneFormSet = inlineformset_factory(Company, Phone, form=forms.ModelForm, fields=('phone_number',), extra=2)
EmailFormSet = inlineformset_factory(Company, Email, form=forms.ModelForm, fields=('email',), extra=2)


class CompanyForm(forms.ModelForm):
    """A class used to create the form for companies

    Attributes (Meta):
        model (class): Database's table
        fields (list): List of fields.
    """  
    class Meta:
        model = Company
        fields = ('name', 'director', 'description')

crm_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.forms import formset_factory
from .models import Company, Address, Phone, Email, Project, Message
from .forms import CompanyForm, AddressFormSet, PhoneFormSet, EmailFormSet


# Create your views here.


class CompanyListView(LoginRequiredMixin, generic.ListView):
    """A class used to represent all companies

    Attributes:
        model (class): Database's table
        paginate_by (int): Number of records on the page
        template_name (str): Name of html template for rendering
    """
    model = Company
    paginate_by = 3
    template_name = 'index.html'


    def get_ordering(self):
        """Method sort records on the page

        Attributes:
            ordering (QuerySet): Sorted list of companies
        """
        ordering = self.request.GET.get('orderby')
        return ordering


class CompanyDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    """A class used to represent information of company

    Attributes:
        model (var): Database's table
        permission_required (str): Page access for manager and administrators
    """
    model = Company
    permission_required = 'crm_app.view_company'


class ProjectDetailView(LoginRequiredMixin, PermissionRequiredMixin, generic.DetailView):
    """A class used to represent information of project

    Attributes:
        model (class): Database's table
        permission_required (str): Page access for manager and administrators
    """
    model = Project
    permission_required = 'crm_app.view_project'


class MessageDetailView(PermissionRequiredMixin, generic.DetailView):
    """A class used to represent information of message

    Attributes:
        model (class): Database's table
        permission_required (str): Page access for manager and administrators
    """
    model = Message
    permission_required = 'crm_app.view_message'



class ProjectListView(PermissionRequiredMixin, generic.ListView):
    """A class used to represent all projects of company

    Attributes:
        template_name (str): Name of html template for rendering
        permission_required (str): Page access for manager and administrators
    """
    template_name = 'crm_app/project_list.html'
    permission_required = 'crm_app.view_project'
    def get_queryset(self):
        """Overriding QuerySet

        Returns:
            QuerySet of projects.
            Can be sorted.
        """
        self.company = get_object_or_404(Company, pk=self.kwargs['pk'])
        return Project.objects.filter(company=self.company).order_by(self.request.GET.get('orderby', 'name'))

    def get_context_data(self, **kwargs):
        """Get the context for this view.

        Returns:
            Context.
        """
        context = super().get_context_data(**kwargs)
        context['company'] = self.company
        context['pk'] = self.kwargs['pk']
        return context


class MessageCompanyListView(PermissionRequiredMixin, generic.ListView):
    """A class used to represent all messages of company

    Attributes:
        template_name (str): Name of html template for rendering
        permission_required (str): Page access for manager and administrators
    """
    template_name = 'crm_app/comp_message_list.html'
    permission_required = 'crm_app.view_message'

    def get_queryset(self):
        """Overriding QuerySet

        Returns:
            QuerySet of messages.
            Can be sorted and filtered.
        """
        self.company = get_object_or_404(Company, pk=self.kwargs['pk'])
        return Message.objects.filter(project__company=self.company).\
        order_by(self.request.GET.get('orderby', 'date_time')).\
        filter(description__contains=self.request.GET.get('filter', ''))

    def get_context_data(self, **kwargs):
        """Get the context for this view.

        Returns:
            Context.
        """
        context = super().get_context_data(**kwargs)
        context['company'] = self.company
        context['pk'] = self.kwargs['pk']
        return context


class MessageProjectListView(PermissionRequiredMixin, generic.ListView):
    """A class used to represent all messages of project

    Attributes:
        template_name (str): Name of html template for rendering
        permission_required (str): Page access for manager and administrators
    """
    template_name = 'crm_app/proj_message_list.html'
    permission_required = 'crm_app.view_message'

    def get_queryset(self):
        """Overriding QuerySet

        Returns:
            QuerySet of messages.
            Can be sorted and filtered.
        """
        self.project = get_object_or_404(Project, pk=self.kwargs['pk'])
        return Message.objects.filter(project=self.project).\
        order_by(self.request.GET.get('orderby', 'date_time')).\
        filter(description__contains=self.request.GET.get('filter', ''))

    def get_context_data(self, **kwargs):
        """Get the context for this view.

        Returns:
            Context.
        """
        context = super().get_context_data(**kwargs)
        context['project'] = self.project
        context['pk'] = self.kwargs['pk']
        return context


class CompanyCreate(PermissionRequiredMixin, CreateView):
    """A class used to create a company

    Attributes:
        model (class): Database's table
        form_class (class): Class inherit from ModelForm
        permission_required (str): Page access for manager and administrators
    """
    model = Company
    form_class = CompanyForm
    permission_required = 'crm_app.add_company'


    def get(self, request, *args, **kwargs):
        """
        Handles GET requests and instantiates blank versions of the form
        and its inline formsets.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        address_form = AddressFormSet()
        phone_form = PhoneFormSet()
        email_form = EmailFormSet()
        return self.render_to_response(
            self.get_context_data(form=form,
                                  address_form=address_form,
                                  phone_form=phone_form,
                                  email_form=email_form))

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance and its inline
        formsets with the passed POST variables and then checking them for
        validity.
        """
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        address_form = AddressFormSet(self.request.POST)
        phone_form = PhoneFormSet(self.request.POST)
        email_form = EmailFormSet(self.request.POST)
        if (form.is_valid() and address_form.is_valid() and
            phone_form.is_valid() and email_form.is_valid()):
            return self.form_valid(form, address_form, phone_form, email_form)
        else:
            return self.form_invalid(form, address_form, phone_form, email_form)

    def form_valid(self, form, address_form, phone_form, email_form):
        """
        Called if all forms are valid. Creates a Company instance along with
        associated Address and Phones and Emails and then redirects to a
        success page.
        """
        self.object = form.save()
        address_form.instance = self.object
        address_form.save()
        phone_form.instance = self.object
        phone_form.save()
        email_form.instance = self.object
        email_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, address_form, phone_form, email_form):
        """
        Called if a form is invalid. Re-renders the context data with the
        data-filled forms and errors.
        """
        return self.render_to_response(
            self.get_context_data(form=form,
                                  address_form=address_form,
                                  phone_form=phone_form,
                                  email_form=email_form))



class CompanyUpdate(PermissionRequiredMixin, UpdateView):
    """A class used to update a company

    Attributes:
        model (class): Database's table
        form_class (class): Class inherit from ModelForm
        permission_required (str): Page access for manager and administrators
    """
    model = Company
    form_class = CompanyForm
    permission_required = 'crm_app.change_company'

    # def get_success_url(self):
    #     return reverse_lazy('company_detail')


    def get_context_data(self, **kwargs):
        """Overriding QuerySet

        Returns:
            QuerySet of companies with addresses, phones and emails.
        """
        context = super(CompanyUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context["address_form"] = AddressFormSet(self.request.POST, instance=self.object)
            context["phone_form"] = PhoneFormSet(self.request.POST, instance=self.object)
            context["email_form"] = EmailFormSet(self.request.POST, instance=self.object)
        else:
            context["address_form"] = AddressFormSet(instance=self.object)
            context["phone_form"] = PhoneFormSet(instance=self.object)
            context["email_form"] = EmailFormSet(instance=self.object)
        return context

    def get(self, request, *args, **kwargs):
        """
        Handles GET requests and instantiates blank versions of the form
        and its inline formsets.
        """
        self.object = self.get_object()
        form_class = self.get_form_class()

crm_app/templates/base_generic.html
{% load static %}

<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'crm_app/styles.css' %}">

   {% block title %}<title>CRM</title>{% endblock %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="nav-item nav-link" href="{% url 'index' %}">Домашняя страница</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">{% block sort %}{% endblock %}</div>
            <div class="navbar-nav mr-auto">{% block filter %}{% endblock %}</div>
            <div class="navbar-nav mr-auto">{% block button %}{% endblock %}</div>
            <div class="navbar-nav mr-auto">{% block button2 %}{% endblock %}</div>
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                {% block password_change %}{% endblock %}
                {% if user.is_staff %}<a class="nav-item nav-link" href="{% url 'admin:index' %}">АдминПанель</a>
                  {% endif %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">{{ user.groups.first }}: {{ user.first_name }} {{ user.last_name }}</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Выход</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Вход</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">{% block content %}{% endblock %}</main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

crm_app/templates/index.html
{% extends "base_generic.html" %}



{% block sort %} 
<form action="" method="get" id="sortProduct">
<div class="dropdown">
  <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Сортировать
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="?orderby=name">По названию</a>
          <a class="dropdown-item" href="?orderby=-name">По названию(в обратном порядке)</a>
          <a class="dropdown-item" href="?orderby=date_create">По дате создания</a>
          <a class="dropdown-item" href="?orderby=-date_create">По дате создания(в обратном порядке)</a>
        </div>
      </li>
</div>
</form>
{% endblock %}
{% block button %}<a class="nav-item nav-link" href="{% url 'company_create' %}">Добавить компанию</a>{% endblock %}
        
{% block content %}

	{% for comp in company_list %}
  <div class="container">
  <div class="row">
    <div class="col">
      <h3><a href="{{ comp.get_absolute_url }}">{{ comp.name }}</a></h3>
    </div>
    <div class="col">
      <p>Директор: {{ comp.director }}</p>
      <p>Телефон: {% for phone in comp.phone_set.all %} {{ phone }}  {% endfor %}</p>
    </div>
    <div class="w-100"></div>
    <div class="col"></div>
    <div class="col">
      <p>Адрес: {% for address in comp.address_set.all %} {{ address }}  {% endfor %}</p>
      <p>Дата создания записи: {{ comp.date_create }}</p>
    </div>
  </div>
  </div><hr><br>
  {% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock %}